databases:
  - name: www_wpschool_it_db
    plan: free
    databaseName: www_wpschool_it
    user: www_13237
    password: uBaKfYFM
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql.next-data.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: www_wpschool_it
      - key: DB_USERNAME
        value: www_13237
      - key: DB_PASSWORD
        value: uBaKfYFM

services:
  - type: web
    plan: free 
    name: laravel_memcache
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: www_wpschool_it_db
          property: connectionString
      - key: DB_CONNECTION
        value: mysql
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: 1
      - key: REAL_IP_HEADER
        value: 1
      - key: SKIP_COMPOSER
        value: 1
